language: bash

sudo: false

services:
  - docker

install:
  - gem install coveralls_reborn
  - gem install bashcov

env:
  - ACONFMGR_INTEGRATION=0
  - ACONFMGR_INTEGRATION=1

script:
 - test/travis.sh
