language: bash

services:
  - docker

# Work around statx "Access denied" problem in containers:
# https://bugzilla.redhat.com/show_bug.cgi?id=1760300#c32
before_install:
  - sudo apt-get update && sudo apt-get install -y libseccomp2

install:
  - gem install coveralls_reborn -v 0.10.0
  - gem install bashcov -v 1.8.2

env:
  - ACONFMGR_INTEGRATION=0
  - ACONFMGR_INTEGRATION=1

script:
 - test/travis.sh

notifications:
  webhooks: https://coveralls.io/webhook
