language: bash

sudo: false

services:
  - docker

install:
  - gem install coveralls_reborn
  - gem install bashcov

script:
 - make -C test ci BUILD_BASH=1
 - docker build -t aconfmgr test/docker
 - docker run -v "$PWD:/aconfmgr:" aconfmgr /aconfmgr/test/docker/run.sh
